# Name: Omar Masri
# Date: 3/10/2024

# Code Description:
# Makefile to compile the program into executable hangman.exe, run the program, and clean the program when we are done

# Changes the file name from hangman.cpp to hangman.exe
Compile:
	g++ -Wall hangman.cpp -o hangman.exe


# Runs the executable file
Run:
	./hangman.exe


# Cleans the executable file when we are done
Clean:
	rm hangman.exe
